### ISSUE TITLE
remove this shit

### ISSUE THREAD

**Issue by ivan123-tty** [valvenewsMega/valvenewsMega#15]
i am serious.

**Comment by CE1CECL** [comment]
> i am serious.

never

@leapofazzam123 lock & close this issue and maybe block @ivan123-ru

**Comment by ivan123-tty** [comment]
> > i am serious.
> 
> never
> 
> @leapofazzam123 lock & close this issue and maybe block @ivan123-ru 

LMFAOOOOOOO

imagine blocking over a fucking emoji though

**Comment by leap0x7b** [comment]
> > i am serious.
> 
> never
> 
> @leapofazzam123 lock & close this issue and maybe block @ivan123-ru

Sure

**Comment by ivan123-tty** [comment]
> > > i am serious.
> > 
> > never
> > 
> > @leapofazzam123 lock & close this issue and maybe block @ivan123-ru
> 
> Sure

💀
